# InterFuser Agent Configuration
# For use with the new consolidated_agent.py

# Model configuration
model_type: interfuser
<<<<<<< HEAD
#model_path: /workspace/leaderboard/team_code/interfuser/interfuser.pth.tar
model_path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/interfuser/interfuser.pth.tar
=======
model_path: /workspace/leaderboard/team_code/interfuser/interfuser.pth.tar
#model_path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/interfuser/interfuser.pth.tar
>>>>>>> 5c6ba0f (trying to set up rsync)

# External config loading (InterFuser's Python config)
#external_config: /workspace/leaderboard/team_code/interfuser/config.py
external_config: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/interfuser/config.py

# Model-specific configuration
model_config:
  architecture: interfuser_baseline
  model_args:
    seq_len: 1
    pred_len: 4
    use_depth: true
    use_semantic: true
    
# Sensor configuration (use default InterFuser sensors)
sensors: default

# Control parameters
control:
  target_speed: 30.0
  brake_threshold: 0.5
  steer_damping: 0.3