# LAV Agent Configuration
<<<<<<< HEAD
<<<<<<< HEAD
# For use with the new consolidated_agent.py

# Model configuration
model_type: lav

# Multi-component model architecture
model_components:
  lidar_model:
<<<<<<< HEAD
    #path: /workspace/leaderboard/team_code/lav/weights/lidar_15.th
    path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/lidar_15.th
    type: checkpoint

  uniplanner:
    #path: /workspace/leaderboard/team_code/lav/weights/uniplanner_15.th
    path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/uniplanner_15.th
    type: checkpoint
    
  bev_model:
    #path: /workspace/leaderboard/team_code/lav/weights/bev_160.th
    path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/bev_160.th
    type: checkpoint
    
  seg_model:
    #path: /workspace/leaderboard/team_code/lav/weights/seg_1.th
    path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/seg_1.th
    type: checkpoint
    
  bra_model:
    #path: /workspace/leaderboard/team_code/lav/weights/bra_10.th
    path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/bra_10.th
=======
    path: /workspace/leaderboard/team_code/lav/weights/lidar_15.th
    #path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/lidar_15.th
    type: checkpoint

  uniplanner:
    path: /workspace/leaderboard/team_code/lav/weights/uniplanner_15.th
    #path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/uniplanner_15.th
    type: checkpoint
    
  bev_model:
    path: /workspace/leaderboard/team_code/lav/weights/bev_160.th
    #path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/bev_160.th
    type: checkpoint
    
  seg_model:
    path: /workspace/leaderboard/team_code/lav/weights/seg_1.th
    #path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/seg_1.th
    type: checkpoint
    
  bra_model:
    path: /workspace/leaderboard/team_code/lav/weights/bra_10.th
    #path: /home/netai/Documents/HPC-CARLA/leaderboard/team_code/lav/weights/bra_10.th
>>>>>>> 5c6ba0f (trying to set up rsync)
    type: checkpoint

# Alternative: Use trace models for faster inference
# model_components:
#   seg_model_trace:
#     path: /workspace/leaderboard/team_code/lav/traced_models/seg_model.pt
#     type: trace

# Model-specific configuration
model_config:
  use_lidar: true
  use_bev: true
  num_waypoints: 10
  
# Sensor configuration - LAV uses BEV and multiple cameras
sensors:
=======
=======
>>>>>>> fe09b6c (annoyign having to rebase every commit but oh well)
model_type: lav

model_components:
  lidar_model:
    path: /workspace/leaderboard/team_code/lav/weights/lidar_15.th
    type: checkpoint
  uniplanner:
    path: /workspace/leaderboard/team_code/lav/weights/uniplanner_15.th
    type: checkpoint
  bev_model:
    path: /workspace/leaderboard/team_code/lav/weights/bev_160.th
    type: checkpoint
  seg_model:
    path: /workspace/leaderboard/team_code/lav/weights/seg_1.th
    type: checkpoint
  bra_model:
    path: /workspace/leaderboard/team_code/lav/weights/bra_10.th
    type: checkpoint

model_config:
  camera_x: 1.3
  camera_z: 2.3
  
# LAV uses specific sensor IDs and configurations
sensors:
  - type: sensor.speedometer
    id: EGO
    
  - type: sensor.other.gnss
    x: 0.0
    y: 0.0
    z: 2.3
    id: GPS
    
  - type: sensor.other.imu
    x: 0.0
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    sensor_tick: 0.05
    id: IMU
    
  - type: sensor.lidar.ray_cast
    x: 0.0
    y: 0.0
    z: 2.3
    yaw: 0.0
    pitch: 0.0
    roll: 0.0
    id: LIDAR
    
  # Three cameras at different angles
  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: -60
    width: 256
    height: 288
    fov: 64
    id: RGB_0
    
  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 0
    width: 256
    height: 288
    fov: 64
    id: RGB_1
    
  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 60
    width: 256
    height: 288
    fov: 64
    id: RGB_2
    
  # Telephoto RGB camera
<<<<<<< HEAD
>>>>>>> 8a07600 (fixing issues w/ model loading)
=======
>>>>>>> fe09b6c (annoyign having to rebase every commit but oh well)
  - type: sensor.camera.rgb
    x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
<<<<<<< HEAD
<<<<<<< HEAD
    width: 900
    height: 256
    fov: 100
    id: rgb_front
    
  - type: sensor.camera.rgb
    x: 0.0
    y: 0.0
    z: 50.0
    roll: 0.0
    pitch: -90.0
    yaw: 0.0
    width: 512
    height: 512
    fov: 110
    id: bev
    
  - type: sensor.camera.semantic_segmentation
    x: 0.0
    y: 0.0
    z: 50.0
    roll: 0.0
    pitch: -90.0
    yaw: 0.0
    width: 512
    height: 512
    fov: 110
    id: semantic_bev
    
  - type: sensor.lidar.ray_cast
    x: 0.0
    y: 0.0
    z: 2.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    id: lidar
    channels: 64
    range: 100
    points_per_second: 1000000
    rotation_frequency: 20
    upper_fov: 10
    lower_fov: -30
    
  - type: sensor.other.gnss
    x: 0.0
    y: 0.0
    z: 0.0
    id: gps
    
  - type: sensor.speedometer
    id: speed

# Control parameters
=======
=======
>>>>>>> fe09b6c (annoyign having to rebase every commit but oh well)
    width: 480
    height: 288
    fov: 40
    id: TEL_RGB

<<<<<<< HEAD
>>>>>>> 8a07600 (fixing issues w/ model loading)
=======
>>>>>>> fe09b6c (annoyign having to rebase every commit but oh well)
control:
  target_speed: 25.0
  brake_threshold: 0.4
  steer_damping: 0.2